#!/bin/sh

[ -f libproject.so.old ] && rm libproject.so.old
[ -f libproject.so ] && mv libproject.so libproject.so.old

[ -f libproject.o.old ] && rm libproject.o.old
[ -f libproject.o ] && mv libproject.o libproject.o.old

gcc -fPIC -Wall -c project-plugin.c `pkg-config --cflags --libs gedit-2.8` -o libproject.o
gcc -shared -Wl,-soname,libproject.so -o libproject.so libproject.o -lc
